### ISSUE TITLE
Top helper command containing bots

### ISSUE THREAD

**Issue by illuminator3** [illuminator3/TJ-Bot#20]
The top helper command still contains bots in the listing. They should not be listed as they don't count as real persons who "help".

**Comment by d3vel0per** [comment]
@illuminator3 I actually got bot's blocked from being saved in messages.
https://github.com/illuminator3/TJ-Bot/blob/master/src/main/java/gg/discord/tj/bot/service/StatisticsService.java#L54

So we need to wait for a month for these records to be eventually purged automatically or do a one time manual cleanup

**Comment by illuminator3** [comment]
I'll probably just do a one-time cleanup on the database
