### ISSUE TITLE
Rewrite to JDA

### ISSUE THREAD

**Issue by Tais993** [illuminator3/TJ-Bot#25]
If possible, rewrite to [JDA](https://github.com/DV8FromTheWorld/JDA/).

JDA has more and better documentation and is more up-to-date from what I know.
Because JDA is the more popular option, more people will be able to contribute and more members of the community are able to help.

If yes, create a "JDA" branche so people can develop it in the background.

**Comment by illuminator3** [comment]
Made a `jda-rewrite` branch
