### ISSUE TITLE
Display the list of commands in a tabular form to aid readability

### ISSUE THREAD

**Issue by d3vel0per** [illuminator3/TJ-Bot#9]
It would be nice to display the results of `^tag` command in a tabular form

eg.
```
All available tags:
 ++                  busychannel  gsdp                 javafxpom  naming     premade                   srp         unsupported     
 abstract            debug        intellij             js         nio        projects                  stacktrace  uri             
 ad                  debugger     interface            lsp        oracle     question                  static      visbility-chart 
 android-getstarted  docker       interface-abstract2  mcve       ossu       regex                     student     w3              
 arch                framework    interrupt            method     parseLine  scanner                   syntax      xy              
 ask                 gist         javadoc              mockdata   person     share                     this                        
 bnf                 git          javafx-swing         mooc       ping       spring-password-handling  typeparam                   
```

but what I am not sure is what if all users don't have a wide enough device to accommodate the width of the table. So this one is debatable

**Comment by lucasstarsz** [comment]
Upon trying this on my phone, both landscape and portrait modes are hard to properly read.
Based on this, 2 or 3 may be a better option than 8.

![Screenshot_20210719-145941_Discord](https://user-images.githubusercontent.com/64715411/126212898-8af07f80-634b-4ba5-8451-efbc2d952e5c.jpg)
![Screenshot_20210719-145915_Discord](https://user-images.githubusercontent.com/64715411/126212903-27581927-10b4-4691-b126-ca1ccb98a405.jpg)

**Comment by lucasstarsz** [comment]
With 3, this looks relatively manageable on portrait mode.
![Screenshot_20210719-150212_Discord](https://user-images.githubusercontent.com/64715411/126213216-95a094e2-f8b3-4547-8fe5-ce99831f0eb4.jpg)
